.gitignore
src/ParticipantManagementService/UpdateParticipant/Participant.cs
src/ParticipantManagementService/UpdateParticipant/Program.cs
src/ParticipantManagementService/UpdateParticipant/Properties/launchSettings.json
src/ParticipantManagementService/UpdateParticipant/UpdateParticipant.cs
src/ParticipantManagementService/UpdateParticipant/UpdateParticipant.csproj
src/ParticipantManagementService/UpdateParticipant/host.json
src/ParticipantManagementService/UpdateParticipant/local.settings.json

Created an UpdateParticipant function that logs the participant Nhs number
Updated gitignore file
https://nhsd-jira.digital.nhs.uk/browse/DTOSS-3585
---

feat: Created UpdateParticipant function

---

tests/EpisodeIntegrationServiceTests/ReceiveDataTests/ReceiveDataTests.cs

Created two test methods for the ReceiveData function, named ReceiveDataTests.
It incorporates tests for a function that did not have any previously.
---

feat: Write unit tests for 'ReceiveData' function

---

compose-mac.yaml
compose-win.yaml
src/MeshIntegrationService/RetrieveMeshFile/RetrieveMeshFile.cs
src/MeshIntegrationService/RetrieveMeshFile/local.settings.json.template

changing Retrieve Mesh function to use an environment variable for the timer expression instead of a hard coded string.
https://nhsd-jira.digital.nhs.uk/browse/DTOSS-5043
---

feat: Dtoss 5043 configure retrieve mesh file function timer with environment variable

---

src/EpisodeIntegrationService/ReceiveData/ReceiveData.cs
tests/EpisodeIntegrationServiceTests/ReceiveDataTests/ReceiveDataTests.cs

changed file name checks in ReceiveData
https://nhsd-jira.digital.nhs.uk/browse/DTOSS-5376?filter=-1
---

feat: changed file name checks in ReceiveData

---

.github/workflows/cicd-1-pull-request.yaml

Fixed the environment_tag variable which was causing the build image stage to be skipped.  
https://github.com/NHSDigital/dtos-service-insights/actions/runs/11891816725
You can see it working correctly in the pipeline run above. 
---

fix: DTOS-00000 fix pipeline trigger

---

src/ReferenceDataService/GetReferenceData/GetReferenceData.cs
src/Shared/Data/IOrganisationLkpRepository.cs
src/Shared/Data/OrganisationLkpRepository.cs
tests/ReferenceDataServiceTests/GetReferenceDataTests/GetReferenceDataTests.cs

fixing type mismatch
https://nhsd-jira.digital.nhs.uk/browse/DTOSS-5042
---

feat: DTOSS-5042 fixing type mismatch

---

infrastructure/tf-core/environments/nft.tfvars

fix: DTOS-0000-fix-linting-issue

---

docs/user-guides/Running_podman_containers.md
scripts/podman-containers/run-containers.sh

Updated documentation and scripts that refer to the compose file for mac.
In line with Cloud Infrastructure changes compose-mac.yaml is now just compose.yaml
---

docs: update compose documentation and scripts

---

infrastructure/tf-audit/diagnostic_settings.tf
infrastructure/tf-audit/locals.tf
infrastructure/tf-audit/log_analytics_workspace.tf
infrastructure/tf-audit/networking.tf
infrastructure/tf-audit/storage.tf
infrastructure/tf-core/app_service_plan.tf
infrastructure/tf-core/diagnostic_settings.tf
infrastructure/tf-core/environments/development.tfvars
infrastructure/tf-core/environments/nft.tfvars
infrastructure/tf-core/function_app.tf
infrastructure/tf-core/key_vault.tf
infrastructure/tf-core/networking.tf
infrastructure/tf-core/storage.tf

Update the terraform so its upto date with Cohort Manager and has the most upto date audit logging occuring. 
Fix a bug with the route table on the NFT environment. 
https://dev.azure.com/nhse-dtos/dtos-service-insights/_build/results?buildId=8477&view=results
---

feat: dtoss 5835 update nft and dev environments to include auditing

---

docs/openapi/openapi-get-participant-screening-episodes.yaml
docs/openapi/openapi-get-participant-screening-profiles.yml

Created the OpenAPI specs
To provide detail to the API consumers
---

docs: Created OpenAPI specs

---

compose-win.yaml
src/BIAnalyticsDataService/CreateParticipantScreeningEpisode/local.settings.json.template
src/BIAnalyticsDataService/CreateParticipantScreeningProfile/local.settings.json.template
src/BIAnalyticsDataService/GetParticipantScreeningEpisodeData/local.settings.json.template
src/BIAnalyticsDataService/GetParticipantScreeningProfileData/local.settings.json.template
src/BIAnalyticsManagementService/CreateParticipantScreeningEpisode/local.settings.json.template
src/BIAnalyticsManagementService/CreateParticipantScreeningProfile/local.settings.json.template
src/BIAnalyticsManagementService/GetParticipantScreeningEpisode/local.settings.json.template
src/BIAnalyticsManagementService/GetParticipantScreeningProfile/local.settings.json.template
src/DemographicsService/GetDemographicsData/local.settings.json.template
src/EpisodeDataService/CreateEpisode/local.settings.json.template
src/EpisodeDataService/GetEpisode/local.settings.json.template
src/EpisodeDataService/UpdateEpisode/local.settings.json.template
src/EpisodeIntegrationService/ReceiveData/local.settings.json.template
src/EpisodeManagementService/CreateUpdateEpisode/local.settings.json.template
src/EpisodeManagementService/GetEpisode/local.settings.json.template
src/MeshIntegrationService/RetrieveMeshFile/local.settings.json.template
src/ParticipantManagementService/GetParticipant/local.settings.json.template
src/ParticipantManagementService/UpdateParticipant/local.settings.json.template
src/ReferenceDataService/GetReferenceData/local.settings.json.template

updating local setting to have environment variable that is set to "development"
---

feat: updating local setting to have environment

---

.env.template
infrastructure/tf-core/environments/development.tfvars
infrastructure/tf-core/environments/nft.tfvars
src/EpisodeIntegrationService/ReceiveData/ReceiveData.cs
src/MeshIntegrationService/RetrieveMeshFile/local.settings.json.template

Blob storage container rename to align with Azure standard
https://nhsd-jira.digital.nhs.uk/browse/DTOSS-6243
---

feat: rename blob storage container

---

compose-win.yaml
compose.yaml
infrastructure/tf-core/environments/development.tfvars
infrastructure/tf-core/environments/nft.tfvars
scripts/database/permissions-dev.sql
scripts/database/permissions-nft.sql

```
Azure Function App names can be up to 60 characters in length. However, it's recommended to keep the name within 32 characters to prevent potential issues with host ID truncation, which can lead to collisions when multiple Function Apps share the same storage account. 
Microsoft Learn
When a Function App name exceeds 32 characters, Azure truncates it to generate the host ID. This truncation can cause conflicts, especially if multiple apps have similar names that result in the same truncated host ID. To avoid such conflicts, it's advisable to keep Function App names concise.
```
This PR is to rename the function app names to avoid collisions. Names agreed to by the Dev team.
---
To ensure the utmost confidentiality and protect your and others privacy, we kindly ask you to NOT including …

fix: dtoss 6292 rename function app names due to length limitation

---

src/BIAnalyticsManagementService/GetParticipantScreeningEpisode/GetParticipantScreeningEpisode.cs
src/BIAnalyticsManagementService/GetParticipantScreeningProfile/GetParticipantScreeningProfile.cs
src/EpisodeDataService/CreateEpisode/CreateEpisode.cs
src/EpisodeDataService/UpdateEpisode/UpdateEpisode.cs
tests/EpisodeDataServiceTests/CreateEpisodeTests/CreateEpisodeTests.cs
tests/EpisodeDataServiceTests/UpdateEpisodeTests/UpdateEpisodeTests.cs

Resolved sonarcloud issues in:
- UpdateEpisode function
- CreateEpisode function
- GetParticipantScreeningEpisode
- GetParticipantScreeningProfile
Update unit tests based on resolved sonarcloud issues
https://nhsd-jira.digital.nhs.uk/browse/DTOSS-6273
---

refactor: resolve sonarcloud issues in main branch

---

.azuredevops/pipelines/cd-infrastructure-int-audit.yaml
.azuredevops/pipelines/cd-infrastructure-int-core.yaml
infrastructure/tf-audit/environments/int.tfvars
infrastructure/tf-core/environments/int.tfvars

feat: DTOSS 5835 deploy int environment

---

.azuredevops/pipelines/cd-infrastructure-dev-audit.yaml
.azuredevops/pipelines/cd-infrastructure-dev-core.yaml
.azuredevops/pipelines/cd-infrastructure-nft-audit.yaml
.azuredevops/pipelines/cd-infrastructure-nft-core.yaml
infrastructure/tf-audit/diagnostic_settings_audit.tf
infrastructure/tf-audit/environments/development.tfvars
infrastructure/tf-audit/environments/int.tfvars
infrastructure/tf-audit/environments/nft.tfvars
infrastructure/tf-audit/log_analytics_workspace.tf
infrastructure/tf-audit/storage.tf
infrastructure/tf-audit/variables.tf
infrastructure/tf-core/diagnostic_settings.tf
infrastructure/tf-core/environments/development.tfvars
infrastructure/tf-core/environments/int.tfvars
infrastructure/tf-core/environments/nft.tfvars
infrastructure/tf-core/function_app.tf
infrastructure/tf-core/key_vault.tf
infrastructure/tf-core/sql_server.tf
infrastructure/tf-core/storage.tf
infrastructure/tf-core/variables.tf
scripts/database/permissions-int.sql

Partial fix, the terraform code has been rebased or made in sync with the Cohort Manager terraform so it now includes Event Hud and so additional diagnostic logging. 
https://dev.azure.com/nhse-dtos/dtos-service-insights/_build/results?buildId=10553&view=results
---

fix: dtoss 6322 container level logs are unavailable in nft

---

infrastructure/tf-core/function_app.tf
infrastructure/tf-core/rbac.tf
infrastructure/tf-core/storage.tf

The PR change to fix the error on: - 
feat: dtoss 6235 create terraform module for azure event grid #102
Also remove unwanted locals wip_rbac_roles_storage
---

fix: pr changes

---

src/MeshIntegrationService/RetrieveMeshFile/Program.cs
src/MeshIntegrationService/RetrieveMeshFile/RetrieveMeshFile.cs
src/MeshIntegrationService/RetrieveMeshFile/RetrieveMeshFile.csproj
src/MeshIntegrationService/RetrieveMeshFile/RetrieveMeshFileConfig.cs
src/MeshIntegrationService/RetrieveMeshFile/local.settings.json.template
src/Shared/Common/BlobStorageHelper.cs
src/Shared/Common/Common.csproj
src/Shared/Common/Extensions/ConfigurationExtension.cs
src/Shared/Common/Interfaces/IBlobStorageHelper.cs
src/Shared/Common/Interfaces/IMeshtoBlobTransferHandler.cs
src/Shared/Common/MeshToBlobTransferHandler.cs
tests/MeshIntegrationServiceTests/RetrieveMeshFileTests/MeshResponseTestHelper.cs
tests/MeshIntegrationServiceTests/RetrieveMeshFileTests/RetrieveMeshFileTests.cs

Add authentication and handshake for mesh mailbox via SSL
Adjust file conversion not to convert filename during mesh to blob transfer
https://nhsd-jira.digital.nhs.uk/browse/DTOSS-6393
---

bugfix: update RetrieveMesh function with Mesh auth handshake and KeyVault.

---

infrastructure/tf-audit/networking.tf
infrastructure/tf-core/networking.tf

fitx: Remove the dns from the vnet module

---

infrastructure/tf-core/environments/development.tfvars
infrastructure/tf-core/environments/int.tfvars
infrastructure/tf-core/environments/nft.tfvars
scripts/database/permissions-dev.sql
scripts/database/permissions-int.sql
scripts/database/permissions-nft.sql

Rename RetrieveMeshFile to use the correct suffix using Terraform. 
---

fix: Rename RetrieveMeshFile to use the correct suffix using Terraform.

---

compose-win.yaml
compose.yaml
src/EpisodeDataService/RetrieveEpisodeReferenceData/Dockerfile
src/EpisodeDataService/RetrieveEpisodeReferenceData/Program.cs
src/EpisodeDataService/RetrieveEpisodeReferenceData/Properties/launchSettings.json
src/EpisodeDataService/RetrieveEpisodeReferenceData/RetrieveEpisodeReferenceData.cs
src/EpisodeDataService/RetrieveEpisodeReferenceData/RetrieveEpisodeReferenceData.csproj
src/EpisodeDataService/RetrieveEpisodeReferenceData/host.json
src/EpisodeDataService/RetrieveEpisodeReferenceData/local.settings.json.template
src/EpisodeManagementService/GetEpisodeReferenceData/Dockerfile
src/EpisodeManagementService/GetEpisodeReferenceData/GetEpisodeReferenceData.cs
src/EpisodeManagementService/GetEpisodeReferenceData/GetEpisodeReferenceData.csproj
src/EpisodeManagementService/GetEpisodeReferenceData/Program.cs
src/EpisodeManagementService/GetEpisodeReferenceData/Properties/launchSettings.json
src/EpisodeManagementService/GetEpisodeReferenceData/host.json
src/EpisodeManagementService/GetEpisodeReferenceData/local.settings.json.template
src/ServiceInsights.sln
src/Shared/Data/EndCodeLkpRepository.cs
src/Shared/Data/EpisodeTypeLkpRepository.cs
src/Shared/Data/FinalActionCodeLkpRepository.cs
src/Shared/Data/IEndCodeLkpRepository.cs
src/Shared/Data/IEpisodeTypeLkpRepository.cs
src/Shared/Data/IFinalActionCodeLkpRepository.cs
src/Shared/Data/IReasonClosedCodeLkpRepository.cs
src/Shared/Data/ReasonClosedCodeLkpRepository.cs
tests/EpisodeDataServiceTests/RetrieveEpisodeReferenceDataTests/RetrieveEpisodeReferenceDataTests.cs
tests/EpisodeDataServiceTests/RetrieveEpisodeReferenceDataTests/RetrieveEpisodeReferenceDataTests.csproj
tests/EpisodeManagementServiceTests/GetEpisodeReferenceDataTests/GetEpisodeReferenceDataTests.cs
tests/EpisodeManagementServiceTests/GetEpisodeReferenceDataTests/GetEpisodeReferenceDataTests.csproj

- Create GetEpisodeReferenceData function in Episode Management Service.
- Create RetrieveEpisodeReferenceData function in Episode Data Service.
- Add unit tests for GetEpisodeReferenceData and RetrieveEpisodeReferenceData functions.
- Update Docker Compose configuration to include GetEpisodeReferenceData and RetrieveEpisodeReferenceData functions.
- Add GetEpisodeReferenceData and RetrieveEpisodeReferenceData functions to solution.
https://nhsd-jira.digital.nhs.uk/browse/DTOSS-6586
---
To ensure the utmost confidentiality and protect your and others privacy, we kindly ask you to NOT including [PII (Personal Identifiable Information) / PID (Personal Identifiable Data)](https://digital.nhs.uk/data-and-information/keeping-data-safe-and-benefitting-the-public) or any other sensitive data in …

feat: DTOSS - 6586 - create get episode reference data function

---

scripts/database/permissions-dev.sql
scripts/database/permissions-int.sql
scripts/database/permissions-nft.sql
src/EpisodeIntegrationService/ReceiveData/ReceiveData.cs
src/EpisodeIntegrationService/ReceiveData/Utils.cs

- update ReceiveData to validate optional Participant values
https://nhsd-jira.digital.nhs.uk/browse/DTOSS-7011
---

fix: update ReceiveData to validate optional Participant values

---

src/EpisodeDataService/UpdateEpisode/Program.cs

Registered missing dependency injection for IEpisodeLkpRepository in the UpdateEpisode function.
Function cannot run without it
---

fix: Registered missing dependency injection in UpdateEpisode

---

infrastructure/tf-core/environments/development.tfvars
infrastructure/tf-core/environments/int.tfvars
infrastructure/tf-core/environments/nft.tfvars

Updated the environment variables for the CreateParticipantScreeningEpisode and CreateParticipantScreeningProfile functions.
To fix bugs caused by incorrectly configured environment variables.
---

fix: Fixed environment variable values

---

infrastructure/tf-core/environments/development.tfvars
infrastructure/tf-core/environments/int.tfvars
infrastructure/tf-core/environments/nft.tfvars

fix: Fixed Terraform environment variables for function endpoint name

---

infrastructure/tf-core/environments/development.tfvars
infrastructure/tf-core/environments/int.tfvars
infrastructure/tf-core/environments/nft.tfvars

Add missing poison-container environment variable to allow Mesh function to work
Also linting of terraform done
https://nhsd-jira.digital.nhs.uk/browse/DTOSS-6702
---

fix: add mising env variable poison-container to mesh function

---

src/BIAnalyticsDataService/GetParticipantScreeningEpisodeData/GetParticipantScreeningEpisodeData.cs
src/BIAnalyticsDataService/GetParticipantScreeningProfileData/GetParticipantScreeningProfileData.cs
src/Shared/Common/PaginationHelper.cs
src/Shared/Data/ParticipantScreeningEpisodeRepository.cs
tests/BIAnalyticsDataServiceTests/GetParticipantScreeningEpisodeDataTests/GetParticipantScreeningEpisodeDataTests.cs
tests/BIAnalyticsDataServiceTests/GetParticipantScreeningProfileDataTests/GetParticipantScreeningProfileDataTests.cs
tests/BIAnalyticsManagementServiceTests/GetParticipantScreeningEpisodeTests/GetParticipantScreeningEpisodeTests.cs
tests/BIAnalyticsManagementServiceTests/GetParticipantScreeningProfileTests/GetParticipantScreeningProfileTests.cs

Making API's fit AC as per https://nhsd-jira.digital.nhs.uk/browse/DTOSS-5764?filter=-1
https://nhsd-jira.digital.nhs.uk/browse/DTOSS-5764?filter=-1
---

feat: dtoss 5764 - implementing get participants data api

---

src/EpisodeDataService/RetrieveEpisodeReferenceData/RetrieveEpisodeReferenceData.cs
src/EpisodeIntegrationService/ReceiveData/BssEpisode.cs
src/EpisodeIntegrationService/ReceiveData/BssSubject.cs
src/EpisodeIntegrationService/ReceiveData/ParticipantReferenceData.cs
src/EpisodeIntegrationService/ReceiveData/ReceiveData.cs
src/Shared/Model/EpisodeReferenceData.cs
tests/EpisodeIntegrationServiceTests/ReceiveDataTests/ReceiveDataTests.cs

- Update ReceiveData function to process historical participants
- Update unit tests
https://nhsd-jira.digital.nhs.uk/browse/DTOSS-6995
---

feat: identify historical participant extracts

---

infrastructure/tf-core/environments/int.tfvars
src/EpisodeDataService/CreateEpisode/CreateEpisode.cs
src/EpisodeDataService/UpdateEpisode/UpdateEpisode.cs
src/ReferenceDataService/GetReferenceData/GetReferenceData.cs
tests/ReferenceDataServiceTests/GetReferenceDataTests/GetReferenceDataTests.cs

Bug fix for [DTOSS-7543](https://nhsd-jira.digital.nhs.uk/browse/DTOSS-7543)
Created a null check in Create and Update Episode 
Updated tests to reflect changes
So that bso_organisation_code can be null and processed successfully in the table
---

fix: Created a null check for create and update episode

---

src/Shared/Common/MeshToBlobTransferHandler.cs

Additional logging for Mesh function, to show GZIP helper function details
https://nhsd-jira.digital.nhs.uk/browse/DTOSS-7573
---

fix: additional GZIP logging for mesh function

---

.gitleaksignore

fix: sign commit

---

.env.template
compose-win.yaml
compose.yaml

Added missing event grid settings for local containers
https://nhsd-jira.digital.nhs.uk/browse/DTOSS-7807
---

fix: add missing event grid settings for local containers
